import jsPDF from "jspdf";


export function generatePDF(summary, overallMood){


const doc = new jsPDF();



const pageWidth = doc.internal.pageSize.getWidth();



// ===== HEADER =====

doc.setFillColor(40, 90, 200);

doc.roundedRect(
10,
10,
pageWidth-20,
35,
5,
5,
"F"
);



doc.setTextColor(255,255,255);

doc.setFontSize(18);

doc.setFont("helvetica","bold");


doc.text(

"Face Expression Analyzer",

pageWidth / 2,

28,

{
align:"center"
}

);


// emoji separately (smaller)

doc.setFontSize(16);

doc.text(

"AI Emotion Report",

pageWidth / 2,

38,

{
align:"center"
}

);





// ===== TITLE =====


doc.setTextColor(0,0,0);

doc.setFontSize(18);

doc.text(

"Emotion Analysis Report",

20,

65

);





// ===== MOOD CARD =====


doc.setFillColor(240,245,255);


doc.roundedRect(

15,

75,

pageWidth-30,

35,

5,

5,

"F"

);



doc.setFontSize(14);

doc.setFont("helvetica","bold");


doc.text(

"Overall Mood",

25,

92

);



doc.setFontSize(18);

doc.setTextColor(40,90,200);


doc.text(

`${overallMood?.toUpperCase()}`,

25,

102

);






// ===== EMOTION DISTRIBUTION =====


doc.setTextColor(0,0,0);


doc.setFontSize(16);

doc.text(

"Emotion Distribution",

20,

140

);



let y=155;



Object.entries(summary)

.forEach(([emotion,value])=>{



// card

doc.setFillColor(250,250,250);


doc.roundedRect(

20,

y-10,

pageWidth-40,

22,

4,

4,

"F"

);



doc.setFontSize(13);



doc.setFont(

"helvetica",

"bold"

);



doc.text(

`${emotion.toUpperCase()}`,

30,

y+4

);





doc.setTextColor(40,90,200);



doc.text(

`${value}%`,

pageWidth-45,

y+4

);



doc.setTextColor(0,0,0);



y+=30;



});







// ===== SUMMARY TEXT =====


doc.setFontSize(14);


doc.text(

"AI Summary",

20,

y+10

);



doc.setFontSize(12);


let message="";


if(overallMood==="happy")

message =
"You appeared positive and cheerful during this session.";


else if(overallMood==="sad")

message =
"You appeared slightly low or relaxed during this session.";


else if(overallMood==="angry")

message =
"You showed signs of intensity or frustration.";


else

message =
"Your expression appeared calm and neutral.";




doc.text(

message,

20,

y+25

);






// ===== DISCLAIMER BOX =====


doc.setFillColor(255,245,230);



doc.roundedRect(

15,

y+40,

pageWidth-30,

35,

5,

5,

"F"

);



doc.setFontSize(10);



doc.text(

"Disclaimer:",

25,

y+55

);


doc.text(

"This is an AI-based expression analysis tool.",

25,

y+65

);


doc.text(

"It is not a medical or psychological report.",

25,

y+72

);







// ===== FOOTER =====


doc.setFontSize(10);


doc.setTextColor(120,120,120);



doc.text(

"Generated by Aman Dwivedi | AI Face Expression Analyzer",

pageWidth/2,

285,

{

align:"center"

}

);




doc.save(

"Emotion_Report.pdf"

);



}